### ISSUE TITLE
Needs more content

### ISSUE THREAD

**Issue by ghost** [RealOrbital32/funny-system#2]
Almost 90% of the planets don't have content in the main system, since they are all so far away, it gets really infuriating.

**Comment by xen-42** [comment]
mfw Jammer has the largest planet mod ever with zero content on the planets

**Comment by ghost** [comment]
> mfw Jammer has the largest planet mod ever with zero content on the planets

True
holden on end??

**Comment by RealOrbital32** [comment]
üse the warps (or start the story by exiting the ship smh) (or use autopilot smh) (or try to explore desfiladeiro without getting lost [impossible challenge]) 💀💀
